services:
  cc_frontend:
    container_name: cc_frontend
    build:
      context: ./frontend
    env_file:
      - ./.env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app-network
    volumes:
      - data_volume:/data

  cc_backend:
    container_name: cc_backend
    build:
      context: ./backend/app
    env_file:
        - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data_volume:/data
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - app-network
  
  cc_whisperlive:
    container_name: cc_whisperlive
    build:
      context: ./backend/whisper_live_server
      args:
        WHISPERLIVE_PORT: ${WHISPERLIVE_PORT}
    env_file:
        - ./.env
    environment:
      WHISPERLIVE_PORT: ${WHISPERLIVE_PORT}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    volumes:
      - data_volume:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - ${WHISPERLIVE_PORT}:${WHISPERLIVE_PORT}
    networks:
      - app-network

  cc_neo4j:
    image: neo4j:enterprise
    container_name: cc_neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}"
      - "${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}"
    volumes:
      - $HOME/neo4j/data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data_volume:
    name: data_volume
    driver: local
