services:
  cc_frontend:
    build:
      context: ./frontend
    env_file:
      - ./.env
    container_name: cc_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - cc_backend
      - cc_neo4j
      - cc_whisper
    networks:
      - app-network
    volumes:
      - data_volume:/data_local

  cc_backend:
    build:
      context: ./backend
    env_file:
        - ./.env
    container_name: cc_backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data_volume:/data_local
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - cc_neo4j
      - cc_whisper
    networks:
      - app-network
  
  cc_whisper:
    build:
      context: ./backend/app/modules/WhisperLive
    container_name: cc_whisper
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "${WHISPER_PORT}:${WHISPER_PORT}"
    networks:
      - app-network

  cc_neo4j:
    image: neo4j:enterprise
    container_name: cc_neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}"
      - "${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}"
    volumes:
      - $HOME/neo4j/data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data_volume:
    name: data_volume
    driver: local
