name: Trigger auto deployment for farfalle-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/backend/**'
    - '.github/workflows/farfalle-backend-AutoDeployTrigger-3e5a49cd-d51c-45b9-93a5-6170d843a4cc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FARFALLEBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FARFALLEBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FARFALLEBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./src/backend/Dockerfile
          registryUrl: farfallebackend.azurecr.io
          registryUsername: ${{ secrets.FARFALLEBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FARFALLEBACKEND_REGISTRY_PASSWORD }}
          containerAppName: farfalle-backend
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: farfallebackend.azurecr.io/farfalle-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


